// <auto-generated />
using System;
using BookTouristRoutes.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookTouristRoutes.DAL.Migrations
{
    [DbContext(typeof(BookTouristRoutesContext))]
    [Migration("20230418083724_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookTouristRoutes.Common.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(677),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/399.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(734)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(796),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1112.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(800)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(817),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/655.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(820)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(832),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/94.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(835)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(848),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/820.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(851)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(864),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/104.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(867)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(879),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1037.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(883)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(896),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/598.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(899)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(911),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1009.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(914)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(927),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/479.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(930)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(945),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/160.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(949)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(964),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/499.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(968)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1027),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/86.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1032)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1049),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/613.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1051)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1059),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/522.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1061)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1069),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/9.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1071)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1079),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1087.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1081)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1088),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/841.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1090)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1097),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/795.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1099)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1106),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/354.jpg",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 300, DateTimeKind.Local).AddTicks(1108)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4319),
                            URL = "https://picsum.photos/640/480/?image=415",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4347)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4381),
                            URL = "https://picsum.photos/640/480/?image=201",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4383)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4392),
                            URL = "https://picsum.photos/640/480/?image=176",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4394)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4403),
                            URL = "https://picsum.photos/640/480/?image=24",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4405)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4413),
                            URL = "https://picsum.photos/640/480/?image=684",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4415)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4423),
                            URL = "https://picsum.photos/640/480/?image=181",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4425)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4433),
                            URL = "https://picsum.photos/640/480/?image=679",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4435)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4443),
                            URL = "https://picsum.photos/640/480/?image=891",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4445)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4453),
                            URL = "https://picsum.photos/640/480/?image=895",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4454)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4464),
                            URL = "https://picsum.photos/640/480/?image=686",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4466)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4536),
                            URL = "https://picsum.photos/640/480/?image=685",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4538)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4547),
                            URL = "https://picsum.photos/640/480/?image=958",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4548)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4556),
                            URL = "https://picsum.photos/640/480/?image=899",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4558)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4566),
                            URL = "https://picsum.photos/640/480/?image=935",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4568)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4576),
                            URL = "https://picsum.photos/640/480/?image=40",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4578)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4585),
                            URL = "https://picsum.photos/640/480/?image=265",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4587)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4595),
                            URL = "https://picsum.photos/640/480/?image=1019",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4597)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4603),
                            URL = "https://picsum.photos/640/480/?image=848",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4605)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4614),
                            URL = "https://picsum.photos/640/480/?image=473",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4615)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4623),
                            URL = "https://picsum.photos/640/480/?image=945",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 301, DateTimeKind.Local).AddTicks(4625)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 304, DateTimeKind.Local).AddTicks(45),
                            Email = "Nicolas_Kohler3@hotmail.com",
                            Name = "Jamil_Wuckert80",
                            Password = "dplJYx2rPdm2EAStnDA3RPiX+gEHe41EU0BJ1teIGUE=",
                            Roles = 1,
                            Salt = "biK19lq7opJRPXer7pOBSWQyXDhUGbW4gFYTSybEbQQ=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 304, DateTimeKind.Local).AddTicks(124)
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 305, DateTimeKind.Local).AddTicks(459),
                            Email = "Destinee_Keebler@yahoo.com",
                            Name = "Sim_Skiles31",
                            Password = "7Uhp2PM6tHpGKRt3TA9Og857W4yuBhAvozXFWlTjm+Q=",
                            Roles = 1,
                            Salt = "HSiXaGaR5sf7Q9+NR22T+BD4LYrFZz1EP+3VZ/YEAWs=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 305, DateTimeKind.Local).AddTicks(464)
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 306, DateTimeKind.Local).AddTicks(568),
                            Email = "Moises87@yahoo.com",
                            Name = "Rosa_Hane58",
                            Password = "sFXJjd5uGFF+USBf7th5ZVN/VplajEQr1E7NbC5NrpA=",
                            Roles = 1,
                            Salt = "HGIA5vRYJJSCv0iYY8WxOVyQX53i5ODEOn49jlZTWqQ=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 306, DateTimeKind.Local).AddTicks(573)
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 307, DateTimeKind.Local).AddTicks(757),
                            Email = "Lisa.Koelpin@hotmail.com",
                            Name = "Frederic.Weimann",
                            Password = "jw+lBnsgkJ9x3N/wwU77rwAgv0vstlTJquxygbGVHdY=",
                            Roles = 0,
                            Salt = "R4t7R36BjQ5J5oY/j9EXqekxAI+IjySd5Qsy6hpt4FU=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 307, DateTimeKind.Local).AddTicks(761)
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 308, DateTimeKind.Local).AddTicks(1201),
                            Email = "Krystal.Koelpin@hotmail.com",
                            Name = "Grant65",
                            Password = "/44icPFLJJcJEswMC34olUorKZtXhWf6+5UokOpi0Yw=",
                            Roles = 0,
                            Salt = "EpEzoybN2XePQJlMB0tIxV3sIZjb8Abb4ekJX79Wb+U=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 308, DateTimeKind.Local).AddTicks(1205)
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 309, DateTimeKind.Local).AddTicks(1310),
                            Email = "Adolfo_Kohler@yahoo.com",
                            Name = "Janae94",
                            Password = "9Bc5jT8VDzPdj0aoAKsxVOMNjbqPKcCr7/0dOM8FDcQ=",
                            Roles = 1,
                            Salt = "5aeaLOOlFDBzhCi3MlDUcWP7UpDv114c3lLUQsUrbuI=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 309, DateTimeKind.Local).AddTicks(1314)
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 310, DateTimeKind.Local).AddTicks(1520),
                            Email = "Estelle.King@gmail.com",
                            Name = "Tyshawn_Littel73",
                            Password = "+OR2i5ood7fEt46leYdz7FYw7K1kkd8SV0igrt6+qpE=",
                            Roles = 1,
                            Salt = "R4qKslwOiM1HCTwZB9YTq0+S7IUES53M0GNomzHN0aw=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 310, DateTimeKind.Local).AddTicks(1523)
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 311, DateTimeKind.Local).AddTicks(2051),
                            Email = "Johanna.Glover@hotmail.com",
                            Name = "Aliya_Gutmann39",
                            Password = "ByGlLtZID3Sf4iNzucQnEyojLJWJTJmuwuC8ldZaxtc=",
                            Roles = 1,
                            Salt = "tyRGlanU2bD3PaoNuFxP79516ug8ugE9AJzsRGWfL8E=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 311, DateTimeKind.Local).AddTicks(2062)
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 312, DateTimeKind.Local).AddTicks(2580),
                            Email = "Ezequiel_Waters@hotmail.com",
                            Name = "Elvera_Hahn35",
                            Password = "8SXppq9pJV3pG5WxyvO12qMZrQF6GzCs25PFi6xVv7k=",
                            Roles = 1,
                            Salt = "iORhO2oAMIDi4WlMA/r1JBcPwL9YukNtZZPRXlpqfrI=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 312, DateTimeKind.Local).AddTicks(2590)
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 313, DateTimeKind.Local).AddTicks(3116),
                            Email = "Miguel.Stehr49@yahoo.com",
                            Name = "Bethany_MacGyver22",
                            Password = "DQ0Vwwl454/HYBAUmWimFZNaXbiIEHq/XxMEwcfQPeA=",
                            Roles = 0,
                            Salt = "1p8E++j0vTW9YLw09c4tuthkzsHwQ9gGT4QAOww4DvE=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 313, DateTimeKind.Local).AddTicks(3126)
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 314, DateTimeKind.Local).AddTicks(3517),
                            Email = "Annetta_Johns@gmail.com",
                            Name = "Chris.Schroeder",
                            Password = "B14NyLLM46btlrUFvqFQWjMrBFMydrqxnUILnkuMqoY=",
                            Roles = 1,
                            Salt = "xkhwgWDgIQzoB2dAnt31nQQHZdCMje7wVjXzhSgjN3c=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 314, DateTimeKind.Local).AddTicks(3527)
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 315, DateTimeKind.Local).AddTicks(3958),
                            Email = "Jerod_Leffler@hotmail.com",
                            Name = "Ryan53",
                            Password = "MZxdZdv3WLKlMuL4sulg1WEwtEZuFOem9d+JfivZNHY=",
                            Roles = 1,
                            Salt = "ZQBAc3BXN9XEBZVHLzlOB6U4S7DHjaoJu5pqDLOBEuw=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 315, DateTimeKind.Local).AddTicks(3969)
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 316, DateTimeKind.Local).AddTicks(4208),
                            Email = "Fanny.Renner@gmail.com",
                            Name = "Javonte.Corkery",
                            Password = "uc7/ZOiYoqJvA6EKjCQTPmtbaO1ZjDHbKPOO06LWbOY=",
                            Roles = 0,
                            Salt = "qhAVnhYg4D9MwnyXJWDNdkJoca7WhAnd8SoA6ZDDnDs=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 316, DateTimeKind.Local).AddTicks(4216)
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 317, DateTimeKind.Local).AddTicks(4544),
                            Email = "Josiah.Langosh@yahoo.com",
                            Name = "Dixie_Douglas",
                            Password = "BPGIvedCG4nhNcTKLhq4xwm1C2YwUXHXlJPcoCLlgEM=",
                            Roles = 1,
                            Salt = "ieIUPPEKUMpDR7vjEKQAAYOPZN2qFlgIvGDl50/v5kY=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 317, DateTimeKind.Local).AddTicks(4550)
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 318, DateTimeKind.Local).AddTicks(4879),
                            Email = "Jazmyne_Casper58@gmail.com",
                            Name = "Bertram_Schaden",
                            Password = "pouepvlzqIVk3rr9oRU/UcsMgTcy0LGBebMi6XUuJAY=",
                            Roles = 0,
                            Salt = "Kpeu5vmhzAT8mE7PzMVLo47ZQSAqY6HzmNRchreZNiw=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 318, DateTimeKind.Local).AddTicks(4883)
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 319, DateTimeKind.Local).AddTicks(5170),
                            Email = "Aimee_Rohan@gmail.com",
                            Name = "Francesca_Hauck17",
                            Password = "0WxNw85uuh/uDtT3/xr/dmk1AtP6ogBs4g5CrcqGGNA=",
                            Roles = 1,
                            Salt = "qOeB3pDugQINMIeJjZYc735E0jdTf3do3pnNjDr0MTQ=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 319, DateTimeKind.Local).AddTicks(5174)
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 320, DateTimeKind.Local).AddTicks(5625),
                            Email = "Linnea39@gmail.com",
                            Name = "Keagan_Gibson",
                            Password = "ZM+F/iBRe7bp0mYWELZArutmnianPOmFXcbkinCb8GI=",
                            Roles = 0,
                            Salt = "SOLh4u9RYqKI4il9Dlet3bHocZSGFv8s0l8HCDm4Kto=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 320, DateTimeKind.Local).AddTicks(5629)
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 321, DateTimeKind.Local).AddTicks(5956),
                            Email = "Sammy23@hotmail.com",
                            Name = "Phyllis.Tromp86",
                            Password = "A8s0Ra/eevp+esy1g7fQHWrAf6/OAZxhJOAzJaJeQn4=",
                            Roles = 1,
                            Salt = "0ig6WItLPiVyHghUuuQ65REe9ROsHMQZ3tTzPw1yISM=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 321, DateTimeKind.Local).AddTicks(5960)
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 322, DateTimeKind.Local).AddTicks(6248),
                            Email = "Kennedi.Purdy0@yahoo.com",
                            Name = "Enos81",
                            Password = "FVSCpOw77TYa9ktsS4zQfEgv8Zj7hUTzwVJ9nNV2nTA=",
                            Roles = 0,
                            Salt = "C667iP0QnPyeyEDWzRsfOKBUZEAH7F/Njg8A4UJSkMQ=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 322, DateTimeKind.Local).AddTicks(6251)
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 323, DateTimeKind.Local).AddTicks(6569),
                            Email = "Mohamed.Cremin43@yahoo.com",
                            Name = "Nikko.Abernathy",
                            Password = "WOpzHRNXeHhqFg09dsLTOKzj17igZiemaCZeSU9uJmA=",
                            Roles = 0,
                            Salt = "NpUF7S2PREdniPp4Lcyh3RFys7SfiwCNT6UqFxb2zfY=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 323, DateTimeKind.Local).AddTicks(6572)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 324, DateTimeKind.Local).AddTicks(6775),
                            Email = "test@gmail.com",
                            Name = "testUser",
                            Password = "e8B/x+na1GkPY8kCm/JNKqibp7EKrdrcV9FFYxCbV/w=",
                            Roles = 0,
                            Salt = "LVy644AXCVfgFxf2EOO8v4amunbCe2P9i13a/jeX2i8=",
                            UpdatedAt = new DateTime(2023, 4, 18, 11, 37, 24, 324, DateTimeKind.Local).AddTicks(6775)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RefreshToken", b =>
                {
                    b.HasOne("BookTouristRoutes.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.User", b =>
                {
                    b.HasOne("BookTouristRoutes.Common.Models.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });
#pragma warning restore 612, 618
        }
    }
}
