// <auto-generated />
using System;
using BookTouristRoutes.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookTouristRoutes.DAL.Migrations
{
    [DbContext(typeof(BookTouristRoutesContext))]
    [Migration("20230428125829_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookTouristRoutes.Common.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8094),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/618.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8135)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8173),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/187.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8176)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8186),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/751.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8188)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8197),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/84.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8199)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8207),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/305.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8209)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8216),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/749.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8218)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8265),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1186.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8267)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8276),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/585.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8278)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8285),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/240.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8287)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8295),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/998.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8297)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8305),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/206.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8307)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8314),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1154.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8316)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8323),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/927.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8325)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8332),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/894.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8334)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8341),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1082.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8343)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8350),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1212.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8352)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8360),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1126.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8362)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8368),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1171.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8370)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8377),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1164.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8379)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8387),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/937.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 317, DateTimeKind.Local).AddTicks(8388)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7203),
                            URL = "https://picsum.photos/640/480/?image=271",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7240)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7275),
                            URL = "https://picsum.photos/640/480/?image=224",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7278)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7287),
                            URL = "https://picsum.photos/640/480/?image=989",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7289)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7299),
                            URL = "https://picsum.photos/640/480/?image=999",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7301)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7309),
                            URL = "https://picsum.photos/640/480/?image=391",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7311)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7362),
                            URL = "https://picsum.photos/640/480/?image=397",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7364)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7374),
                            URL = "https://picsum.photos/640/480/?image=638",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7376)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7384),
                            URL = "https://picsum.photos/640/480/?image=290",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7386)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7394),
                            URL = "https://picsum.photos/640/480/?image=497",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7396)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7405),
                            URL = "https://picsum.photos/640/480/?image=280",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7406)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7415),
                            URL = "https://picsum.photos/640/480/?image=39",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7417)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7425),
                            URL = "https://picsum.photos/640/480/?image=335",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7426)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7435),
                            URL = "https://picsum.photos/640/480/?image=323",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7437)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7444),
                            URL = "https://picsum.photos/640/480/?image=289",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7446)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7453),
                            URL = "https://picsum.photos/640/480/?image=223",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7455)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7463),
                            URL = "https://picsum.photos/640/480/?image=259",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7465)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7473),
                            URL = "https://picsum.photos/640/480/?image=726",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7474)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7482),
                            URL = "https://picsum.photos/640/480/?image=616",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7484)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7492),
                            URL = "https://picsum.photos/640/480/?image=950",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7494)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7502),
                            URL = "https://picsum.photos/640/480/?image=422",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 319, DateTimeKind.Local).AddTicks(7504)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RouteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookedSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 322, DateTimeKind.Local).AddTicks(5490),
                            Email = "Giovanni.Harvey@hotmail.com",
                            Name = "Donato.Gottlieb61",
                            Password = "NyDoVvpfN0ZjJEdEaCDsEgWtakEnWB0NX0om4FkAkng=",
                            Role = 0,
                            Salt = "Vv1lN1+FkIGYeoMCuudY8U+ciqCkitKsmxcb+c0aXh4=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 322, DateTimeKind.Local).AddTicks(5585)
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 323, DateTimeKind.Local).AddTicks(6000),
                            Email = "Zena.Leffler65@yahoo.com",
                            Name = "Geovany.Kozey34",
                            Password = "m75Cn78W2EuTo2VcxBZOdo3EsOoxnZzBhhgpXVwmujA=",
                            Role = 0,
                            Salt = "aTBCorWSgINAT9AxMuevMGp+lOelDFLLDZ2jwSvcw0c=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 323, DateTimeKind.Local).AddTicks(6006)
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 324, DateTimeKind.Local).AddTicks(6223),
                            Email = "Joanny.Ondricka78@hotmail.com",
                            Name = "Destinee42",
                            Password = "4gCjzODKM3QTitybAH0e8IS/0wpBZccztvByhRZshEs=",
                            Role = 1,
                            Salt = "lYVcokL0R9gVowCGERMlQ8a/1kxpnypIC0RETJdnIq0=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 324, DateTimeKind.Local).AddTicks(6228)
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 325, DateTimeKind.Local).AddTicks(6433),
                            Email = "Allen_Okuneva@gmail.com",
                            Name = "Lempi.Oberbrunner67",
                            Password = "1Qc0Tu068NnVlDOtiJSuqGxrhXRyZelN0UbiCrd/b18=",
                            Role = 1,
                            Salt = "fgpO7a094mY75ceOoEq3DeqXgNi/69cz4lStfVCHpFU=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 325, DateTimeKind.Local).AddTicks(6438)
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 326, DateTimeKind.Local).AddTicks(6485),
                            Email = "Shaniya72@gmail.com",
                            Name = "Trenton_Blanda",
                            Password = "jPF8mqCH/DROuuQ5hMsTnI4jSf8PW7xz8ttWXtiuyOo=",
                            Role = 0,
                            Salt = "q4psaw1LPl/IagWoEJrm/TCFmFtuPExYWXK13SLS2r8=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 326, DateTimeKind.Local).AddTicks(6490)
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 327, DateTimeKind.Local).AddTicks(6533),
                            Email = "Emmanuel99@gmail.com",
                            Name = "Wilton54",
                            Password = "aG26X+BMjNG8y6ZvAGeIPMtN//Zj6llejpTjYKKiOsc=",
                            Role = 1,
                            Salt = "lMObkZSLma21hU26MzhK6jKN0rx3LMxMr3CEIMeOWO4=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 327, DateTimeKind.Local).AddTicks(6536)
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 328, DateTimeKind.Local).AddTicks(6638),
                            Email = "Krista28@yahoo.com",
                            Name = "Joannie.Ondricka14",
                            Password = "yWb2/ZzukMYIcxEqzaO+VyElmAQDOauCtgKfoG6Sr+0=",
                            Role = 1,
                            Salt = "t+Vs8MfEq0D1RxPTxxYgxlstcyMDA6MsIw2Asra+r8c=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 328, DateTimeKind.Local).AddTicks(6642)
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 329, DateTimeKind.Local).AddTicks(6828),
                            Email = "Reynold_Wisozk29@gmail.com",
                            Name = "Maye_Zieme41",
                            Password = "roO7M0r8/N8R+hQkeZbka52SRkbHfcke+npAumKJOmY=",
                            Role = 1,
                            Salt = "bhR0aMSWPbbRhuaTkpucUliVzAYthv607SJ55BBobCc=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 329, DateTimeKind.Local).AddTicks(6831)
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 330, DateTimeKind.Local).AddTicks(6958),
                            Email = "Dennis.Nitzsche@gmail.com",
                            Name = "Zackary_Heller",
                            Password = "OsLSXR8maFsKMJrKF1JZGZln6o+Rvp/Eip7T+36jdYw=",
                            Role = 0,
                            Salt = "3J4KXVNT2yjYMrwZjwG062WVWJnPyLXKuq3U63rW0p4=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 330, DateTimeKind.Local).AddTicks(6962)
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 331, DateTimeKind.Local).AddTicks(7023),
                            Email = "Carmelo.Mitchell@yahoo.com",
                            Name = "Alphonso70",
                            Password = "EzNq1fXnVVEu29LZ1kbas1Vt+UR/kmrGL/8qjKn3v3E=",
                            Role = 0,
                            Salt = "NYsXIfn2qaP0n8xKdvt0gPfbV7+/F5JKf/EF/9KRzqg=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 331, DateTimeKind.Local).AddTicks(7027)
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 332, DateTimeKind.Local).AddTicks(7111),
                            Email = "Agustin.Stoltenberg@gmail.com",
                            Name = "Eldridge.Schmeler46",
                            Password = "FSmV/SiWWN9h4qeM5u9UBH2p2kH1T5kQmRb561D7ggo=",
                            Role = 0,
                            Salt = "4iqhMqCGIjA25wpV6ZEdLyP8T+yZ+7yzrnLcu2Au9QI=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 332, DateTimeKind.Local).AddTicks(7115)
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 333, DateTimeKind.Local).AddTicks(7424),
                            Email = "Rafael64@gmail.com",
                            Name = "Soledad71",
                            Password = "qhlvVuQQS5IizL4zkvec6ul970lhUfdFgpSXK9HtI6Y=",
                            Role = 0,
                            Salt = "m3da7akovqKCD2gDvNFzhnpVXhl2mYzwxT8T53a1eTM=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 333, DateTimeKind.Local).AddTicks(7431)
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 334, DateTimeKind.Local).AddTicks(7546),
                            Email = "Federico90@gmail.com",
                            Name = "Charlotte.Blanda",
                            Password = "lnuX5RdNg0M44GBsniuDd8aw2TqbdHGj5MwZ1bLuG7M=",
                            Role = 1,
                            Salt = "ACnlY71+1RwmfsCdl6bqtQcokwt41uUBZU/8FHY3WHU=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 334, DateTimeKind.Local).AddTicks(7550)
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 335, DateTimeKind.Local).AddTicks(7733),
                            Email = "Javon71@hotmail.com",
                            Name = "Laury_Mraz",
                            Password = "1YlBtUbUXU91/66zQ6qSy7h6Se+PATm/YOPsd+IvjY8=",
                            Role = 0,
                            Salt = "Bt9IqouA9M1ede1D31h2yqbfXDPrPzxrbj+yehz0Ypo=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 335, DateTimeKind.Local).AddTicks(7739)
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 336, DateTimeKind.Local).AddTicks(7796),
                            Email = "Kristoffer77@hotmail.com",
                            Name = "Judah.Rowe74",
                            Password = "RWcvf0/y/WN1YFtgeBZs4OW1NAy61CWIMRRjDoLv/yE=",
                            Role = 1,
                            Salt = "lheO7k2temW1jhs4bMHRHpW5lB2wujqp6SWCgEhxdv8=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 336, DateTimeKind.Local).AddTicks(7801)
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 337, DateTimeKind.Local).AddTicks(7887),
                            Email = "Kyle36@yahoo.com",
                            Name = "Emilie.Lind",
                            Password = "b9nkAmz6jhApROMZlFmOTAe2C5lRh0I0vWxZsvTiI3s=",
                            Role = 0,
                            Salt = "899PkkM+6k77fZAFS1CRZHWRnqa8GJEBuABUbaqOfpE=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 337, DateTimeKind.Local).AddTicks(7891)
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 338, DateTimeKind.Local).AddTicks(8023),
                            Email = "Santiago.Cummerata75@yahoo.com",
                            Name = "Zelda.Kemmer",
                            Password = "eg98aQfKsWa7qRmnzgnAsR1QJxCpBPopXiDptLsCcrc=",
                            Role = 0,
                            Salt = "mNPWv5B8fvMC1/Jgl6GjIIiWw6F9UPFMI16YB0d4/gI=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 338, DateTimeKind.Local).AddTicks(8026)
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 339, DateTimeKind.Local).AddTicks(8052),
                            Email = "Daren51@yahoo.com",
                            Name = "Rae_Wunsch36",
                            Password = "dbE0VF7ExE5d0w8cpzrYXUdSeily60Oa96wZ17ENVPU=",
                            Role = 0,
                            Salt = "EUmVBexaMXvYVN42a5+9+5zdJW075fkSF+7gTb+LMkQ=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 339, DateTimeKind.Local).AddTicks(8055)
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 340, DateTimeKind.Local).AddTicks(8102),
                            Email = "Bartholome_Leuschke50@yahoo.com",
                            Name = "Mckayla.Rosenbaum60",
                            Password = "gOuMtxk6JbG4Q9CzdxmgGZZivI+2CN+7yasyk0K4/5w=",
                            Role = 1,
                            Salt = "k9wT8Ke2r51hX+0HDFPTzjEDSTTbuyp+z3EGBMVXR8o=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 340, DateTimeKind.Local).AddTicks(8106)
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 341, DateTimeKind.Local).AddTicks(8195),
                            Email = "Cordia41@yahoo.com",
                            Name = "Jovan90",
                            Password = "IO9gwWoxfQjKYklVa4Q8nZRZhfVAHVslsCx0L4rjxDo=",
                            Role = 0,
                            Salt = "lJc+Pw1ZpEFeuDahzYEGXi+LrZ6UC2d+03PPSGbncg0=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 341, DateTimeKind.Local).AddTicks(8198)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 342, DateTimeKind.Local).AddTicks(8194),
                            Email = "test@gmail.com",
                            Name = "testUser",
                            Password = "HGU0aoEkyLsXkVAMunuaAgC9IlAt9ZX5i05BxfPwhx4=",
                            Role = 0,
                            Salt = "4mYxRrqkL+jn5koJRSmemVdKJd9XsuLYURby0nmWgUw=",
                            UpdatedAt = new DateTime(2023, 4, 28, 15, 58, 29, 342, DateTimeKind.Local).AddTicks(8194)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RefreshToken", b =>
                {
                    b.HasOne("BookTouristRoutes.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.User", b =>
                {
                    b.HasOne("BookTouristRoutes.Common.Models.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });
#pragma warning restore 612, 618
        }
    }
}
