// <auto-generated />
using System;
using BookTouristRoutes.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookTouristRoutes.DAL.Migrations
{
    [DbContext(typeof(BookTouristRoutesContext))]
    [Migration("20230424155850_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookTouristRoutes.Common.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(587),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1016.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(626)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(661),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/626.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(664)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(673),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/697.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(675)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(683),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1122.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(685)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(693),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/636.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(695)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(702),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/641.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(704)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(711),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/510.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(713)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(720),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/380.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(722)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(729),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/695.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(731)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(738),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/653.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(796)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(816),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/438.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(820)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(829),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/655.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(831)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(838),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/699.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(841)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(848),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1043.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(850)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(857),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1143.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(859)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(866),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/80.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(868)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(875),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/71.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(877)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(885),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/413.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(886)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(893),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/161.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(895)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(903),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/305.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 83, DateTimeKind.Local).AddTicks(905)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8201),
                            URL = "https://picsum.photos/640/480/?image=851",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8234)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8266),
                            URL = "https://picsum.photos/640/480/?image=238",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8268)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8278),
                            URL = "https://picsum.photos/640/480/?image=840",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8280)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8288),
                            URL = "https://picsum.photos/640/480/?image=182",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8290)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8298),
                            URL = "https://picsum.photos/640/480/?image=223",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8299)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8307),
                            URL = "https://picsum.photos/640/480/?image=443",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8309)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8317),
                            URL = "https://picsum.photos/640/480/?image=41",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8319)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8326),
                            URL = "https://picsum.photos/640/480/?image=786",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8328)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8361),
                            URL = "https://picsum.photos/640/480/?image=1020",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8363)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8372),
                            URL = "https://picsum.photos/640/480/?image=510",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8374)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8382),
                            URL = "https://picsum.photos/640/480/?image=927",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8384)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8392),
                            URL = "https://picsum.photos/640/480/?image=941",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8393)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8402),
                            URL = "https://picsum.photos/640/480/?image=350",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8404)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8412),
                            URL = "https://picsum.photos/640/480/?image=909",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8414)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8422),
                            URL = "https://picsum.photos/640/480/?image=380",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8424)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8432),
                            URL = "https://picsum.photos/640/480/?image=810",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8434)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8441),
                            URL = "https://picsum.photos/640/480/?image=504",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8443)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8451),
                            URL = "https://picsum.photos/640/480/?image=426",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8453)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8461),
                            URL = "https://picsum.photos/640/480/?image=464",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8463)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8471),
                            URL = "https://picsum.photos/640/480/?image=311",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 84, DateTimeKind.Local).AddTicks(8473)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookedSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 87, DateTimeKind.Local).AddTicks(5579),
                            Email = "Joe_Ondricka@gmail.com",
                            Name = "Lew_Lang",
                            Password = "kiysWSRsiJOy08/bEn0dvPIpELVJFGoqBuFwMqScUyE=",
                            Role = 1,
                            Salt = "FdziYMSwQvzwL2Y9aZ5aSJ3wjFTpu1P1vtd00SWGYvk=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 87, DateTimeKind.Local).AddTicks(5668)
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 88, DateTimeKind.Local).AddTicks(5995),
                            Email = "Alessandra23@hotmail.com",
                            Name = "George.Thiel",
                            Password = "OydFzIXWLUxw4groNCsclFgMWXYbo/mYHQcUZ+XdLQ4=",
                            Role = 1,
                            Salt = "dFpggXkWFHRdRhorkPnurAhW7ONJWYyZwU/Ov7FqpiI=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 88, DateTimeKind.Local).AddTicks(5999)
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 89, DateTimeKind.Local).AddTicks(6246),
                            Email = "Michelle.Raynor88@yahoo.com",
                            Name = "Jodie_Donnelly",
                            Password = "wE5yVsalo0YVOPl2sLfjjPvEkPtaERm+UNssWWIuoT0=",
                            Role = 0,
                            Salt = "gN8znBWmB/0LOm7TXqKuAXuTXRs7fGwKMduKd2vcwhw=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 89, DateTimeKind.Local).AddTicks(6250)
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 90, DateTimeKind.Local).AddTicks(6496),
                            Email = "Flossie_Satterfield@gmail.com",
                            Name = "Precious24",
                            Password = "WGOlznb6Bx3ADz74WZlZ0tf24rAZD/AuAiErTc9T754=",
                            Role = 0,
                            Salt = "yelXmZvqZI/lLz8XGGbNq56MSChrycYcZRkCAy5ip3k=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 90, DateTimeKind.Local).AddTicks(6501)
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 91, DateTimeKind.Local).AddTicks(6592),
                            Email = "Daren.Ratke95@gmail.com",
                            Name = "Ryann33",
                            Password = "gBVnGWGO1KQrrmFuAF2v0+0CT0Sq4cxjzHN7OxX0suM=",
                            Role = 1,
                            Salt = "42o5Bqr4XuzUJu9r0kvqBfDT+fD0ayb7vqqU5ljAbpw=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 91, DateTimeKind.Local).AddTicks(6596)
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 92, DateTimeKind.Local).AddTicks(6690),
                            Email = "Giuseppe29@yahoo.com",
                            Name = "Jennifer.Rohan",
                            Password = "zLSfS0I1g0efY1vCfVmDzdca2771dFQsIOny8NjWYaA=",
                            Role = 1,
                            Salt = "9N5M6NsycL3iGd7Y6neUXHJVlF2bg8posTw53DNrNjk=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 92, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 93, DateTimeKind.Local).AddTicks(6752),
                            Email = "Tracy11@gmail.com",
                            Name = "Mustafa41",
                            Password = "uxcqQXuuF4MEh27PsKDUblaexhVK5UZxnaR4UzgRFQs=",
                            Role = 0,
                            Salt = "5vP/zTkb36wEcae6MsAsSDLjbpxBkvtlFI2vvxD6tM8=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 93, DateTimeKind.Local).AddTicks(6756)
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 94, DateTimeKind.Local).AddTicks(6994),
                            Email = "Fernando19@hotmail.com",
                            Name = "Madison_Connelly39",
                            Password = "8Z9Ldhn1FMP+P/iyMyC9ZgoVMkF1fpt8yx22QoqjFPQ=",
                            Role = 0,
                            Salt = "uOvuoWpVxWGDABdNlvt6ulQz/w51B5ea5GVIdFEII1E=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 94, DateTimeKind.Local).AddTicks(6999)
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 95, DateTimeKind.Local).AddTicks(7163),
                            Email = "Isabelle.Muller43@yahoo.com",
                            Name = "Gavin.Sanford63",
                            Password = "PO8gcc9gKp5Ih55JCBh5+FgtukKHSxZZ6r4jN6cf8kA=",
                            Role = 0,
                            Salt = "MSV1MZdfDiEJjqbjYGGWGCce6eWF4eSuHlrbZTU8mqY=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 95, DateTimeKind.Local).AddTicks(7166)
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 96, DateTimeKind.Local).AddTicks(7194),
                            Email = "Naomie_Gulgowski33@hotmail.com",
                            Name = "Claudia_Sauer",
                            Password = "j5nmkPdARgSybN3E0QoRrDtGvnY5ulBtaPw+qgjpLMs=",
                            Role = 0,
                            Salt = "A5n1+NSRe/WU7WlOUvTh76Il60gEXNXwZmo1LeeOBsw=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 96, DateTimeKind.Local).AddTicks(7196)
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 97, DateTimeKind.Local).AddTicks(7370),
                            Email = "Leon_Considine92@gmail.com",
                            Name = "Dexter.Pfannerstill72",
                            Password = "t1+ij7nAaUklxqYPtQc3UdJ2kmUJqGPUOkjmChpOOAU=",
                            Role = 1,
                            Salt = "ivHgEH3shGRNaYuoP55L6SGUlp5/bWcAR32+F8zzltU=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 97, DateTimeKind.Local).AddTicks(7373)
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 98, DateTimeKind.Local).AddTicks(7518),
                            Email = "Desiree61@gmail.com",
                            Name = "Newton.Kertzmann94",
                            Password = "er31xbQB/O75TDweqF0J2IfhjYviyiSo232SwnOAqG4=",
                            Role = 0,
                            Salt = "xcQQMTBd7f45usdVx2C9ZIAH7IRazLPPLChgh18T2Ig=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 98, DateTimeKind.Local).AddTicks(7522)
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 99, DateTimeKind.Local).AddTicks(7626),
                            Email = "Tristian_Fay@gmail.com",
                            Name = "Brendon.Erdman",
                            Password = "cr5Dmdj3cGWR00HqMxgxPOe3LQF/rV9KcubPUbp9v2I=",
                            Role = 0,
                            Salt = "sABhdwdjP23AceoP0HA2e6+LTqnbFoNIS/ADzIWIlFs=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 99, DateTimeKind.Local).AddTicks(7629)
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 100, DateTimeKind.Local).AddTicks(7735),
                            Email = "Friedrich_Emard@gmail.com",
                            Name = "Patricia_Dietrich",
                            Password = "0l4AEd1QqTr8jIKpccIqvYNI850W3tPK2YIMcYxIwXM=",
                            Role = 1,
                            Salt = "U8mDWz9hs7AIVEWMNMAVaGlC4q+K8WISdk2I/fVPjnM=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 100, DateTimeKind.Local).AddTicks(7738)
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 101, DateTimeKind.Local).AddTicks(7769),
                            Email = "Candace10@yahoo.com",
                            Name = "Coty83",
                            Password = "ZIusQTS1JAnzWJcV2GWGwBuOyUw1JBzSMWkFEg/g+bE=",
                            Role = 1,
                            Salt = "VD1NjHRN8GMMwvw7G7PT3bhSnIyYFStCN5xej863nz0=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 101, DateTimeKind.Local).AddTicks(7772)
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 102, DateTimeKind.Local).AddTicks(7923),
                            Email = "Otho_Bruen@hotmail.com",
                            Name = "Leslie_Morissette",
                            Password = "oHHdX3FYD2Mklv38uJtsFG81Db8m5dAZgxjJSErOtvo=",
                            Role = 0,
                            Salt = "v8G3DY1+W+O8ja/WzYpsCMCqKuRV88UrBFlU0LDaetE=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 102, DateTimeKind.Local).AddTicks(7926)
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 103, DateTimeKind.Local).AddTicks(8034),
                            Email = "Cory.Pfannerstill41@yahoo.com",
                            Name = "Wallace42",
                            Password = "08r7R1odQBjhnn9lfTlK7czR0PAN4CUJ8ETM3pn28T4=",
                            Role = 1,
                            Salt = "BkRft1oelFVomuXQHBCqaoeWZuyf6nwXIKZWxpRC3ao=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 103, DateTimeKind.Local).AddTicks(8037)
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 104, DateTimeKind.Local).AddTicks(8073),
                            Email = "Cordell_Nolan@yahoo.com",
                            Name = "Sonny_Wuckert",
                            Password = "zwoG7UE3VHsW8KGESLp+5oVMF8gHzZlRTQW9OMASguY=",
                            Role = 1,
                            Salt = "pmsAKuelCx30tWIYFMXwnyEVKDyqsBwzZb44rBm9zTI=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 104, DateTimeKind.Local).AddTicks(8076)
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 105, DateTimeKind.Local).AddTicks(8281),
                            Email = "Pink.Runolfsdottir@gmail.com",
                            Name = "Orie_Blick",
                            Password = "vnJKwdR8wDO5z5G3f4nYcL+Jxq92FILlrVSNI0f7hd8=",
                            Role = 1,
                            Salt = "UsYvdp+Ku3e4UU/1CebvK25d9gembp2tyQjG3e09njE=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 105, DateTimeKind.Local).AddTicks(8286)
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 106, DateTimeKind.Local).AddTicks(8386),
                            Email = "Karli.Cole@gmail.com",
                            Name = "Antonietta.McDermott",
                            Password = "e6F5tVtsRLsoln8ABl42bQNWt5tUSKpRDsdqbJAWTkE=",
                            Role = 1,
                            Salt = "sNlmx1bokn9TAa6FfNtdRX2MKCtYvUQM1FZg7i0FcUU=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 106, DateTimeKind.Local).AddTicks(8389)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 107, DateTimeKind.Local).AddTicks(8328),
                            Email = "test@gmail.com",
                            Name = "testUser",
                            Password = "1gjlXYaBYtJKvOWQ5gcnSU70eqvCaTP7YBJwR4IMtdw=",
                            Role = 0,
                            Salt = "KpzMF/6xb5yAFO98417gJXAepgxbeAsrMbVGesruEm0=",
                            UpdatedAt = new DateTime(2023, 4, 24, 18, 58, 50, 107, DateTimeKind.Local).AddTicks(8328)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RefreshToken", b =>
                {
                    b.HasOne("BookTouristRoutes.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.User", b =>
                {
                    b.HasOne("BookTouristRoutes.Common.Models.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });
#pragma warning restore 612, 618
        }
    }
}
