// <auto-generated />
using System;
using BookTouristRoutes.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookTouristRoutes.DAL.Migrations
{
    [DbContext(typeof(BookTouristRoutesContext))]
    [Migration("20230428165304_ActualRelease")]
    partial class ActualRelease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookTouristRoutes.Common.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4175),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/969.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4215)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4255),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/421.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4258)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4267),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1212.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4269)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4276),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/970.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4278)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4285),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/514.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4287)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4294),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/592.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4296)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4304),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/150.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4306)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4314),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/53.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4315)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4323),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/231.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4325)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4332),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/432.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4334)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4341),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/123.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4343)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4350),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1091.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4352)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4359),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/511.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4361)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4369),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/650.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4371)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4378),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/731.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4380)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4388),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/268.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4389)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4420),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/775.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4422)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4430),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/997.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4432)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4439),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/348.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4441)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4448),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/414.jpg",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 384, DateTimeKind.Local).AddTicks(4449)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1318),
                            URL = "https://picsum.photos/640/480/?image=175",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1352)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1387),
                            URL = "https://picsum.photos/640/480/?image=1045",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1390)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1400),
                            URL = "https://picsum.photos/640/480/?image=287",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1401)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1410),
                            URL = "https://picsum.photos/640/480/?image=505",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1412)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1421),
                            URL = "https://picsum.photos/640/480/?image=852",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1422)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1431),
                            URL = "https://picsum.photos/640/480/?image=422",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1432)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1441),
                            URL = "https://picsum.photos/640/480/?image=673",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1443)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1451),
                            URL = "https://picsum.photos/640/480/?image=714",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1453)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1461),
                            URL = "https://picsum.photos/640/480/?image=146",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1463)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1470),
                            URL = "https://picsum.photos/640/480/?image=825",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1472)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1480),
                            URL = "https://picsum.photos/640/480/?image=637",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1482)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1489),
                            URL = "https://picsum.photos/640/480/?image=1054",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1491)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1522),
                            URL = "https://picsum.photos/640/480/?image=1067",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1524)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1533),
                            URL = "https://picsum.photos/640/480/?image=757",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1535)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1543),
                            URL = "https://picsum.photos/640/480/?image=691",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1544)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1552),
                            URL = "https://picsum.photos/640/480/?image=88",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1554)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1562),
                            URL = "https://picsum.photos/640/480/?image=860",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1563)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1571),
                            URL = "https://picsum.photos/640/480/?image=466",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1572)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1580),
                            URL = "https://picsum.photos/640/480/?image=434",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1582)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1590),
                            URL = "https://picsum.photos/640/480/?image=806",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 386, DateTimeKind.Local).AddTicks(1592)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RouteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookedSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(6658),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Destination = "West Norrisfort",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(7161),
                            Name = "New Dewittport",
                            Price = 6428.207681824902841m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(7123),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(6658)
                        },
                        new
                        {
                            Id = 2,
                            BookedSeats = 1,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8432),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Destination = "Kamronport",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8511),
                            Name = "South Carleton",
                            Price = 6350.130278032564198m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8506),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8432)
                        },
                        new
                        {
                            Id = 3,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8564),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Destination = "West Daphneeview",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8636),
                            Name = "Schinnerhaven",
                            Price = 7893.261257630721301m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8632),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8564)
                        },
                        new
                        {
                            Id = 4,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8681),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Destination = "West Christaville",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8720),
                            Name = "Whiteside",
                            Price = 2996.348276955336049m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8717),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8681)
                        },
                        new
                        {
                            Id = 5,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8786),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Destination = "Champlinville",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8822),
                            Name = "Dickinsonport",
                            Price = 9491.057778056975515m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8819),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8786)
                        },
                        new
                        {
                            Id = 6,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8897),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Destination = "East Tia",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8933),
                            Name = "Greenside",
                            Price = 6915.330577551414061m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8930),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8897)
                        },
                        new
                        {
                            Id = 7,
                            BookedSeats = 1,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8966),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Destination = "Susannaland",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9031),
                            Name = "Lake Jordyfurt",
                            Price = 7818.695210549994418m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9028),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(8966)
                        },
                        new
                        {
                            Id = 8,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9064),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Destination = "Lake Amandaland",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9104),
                            Name = "New Joannybury",
                            Price = 5907.85310705725576m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9102),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9064)
                        },
                        new
                        {
                            Id = 9,
                            BookedSeats = 1,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9165),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Destination = "North Velmafort",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9200),
                            Name = "New Meda",
                            Price = 4556.595666817335547m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9198),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9165)
                        },
                        new
                        {
                            Id = 10,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9260),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Destination = "North Violet",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9295),
                            Name = "Aileenview",
                            Price = 2016.874100393373583m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9292),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9260)
                        },
                        new
                        {
                            Id = 11,
                            BookedSeats = 1,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9326),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Destination = "North Andres",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9384),
                            Name = "Port Thaddeus",
                            Price = 3551.343009605448661m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9381),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9326)
                        },
                        new
                        {
                            Id = 12,
                            BookedSeats = 1,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9414),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Destination = "New Chadd",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9452),
                            Name = "East Albaberg",
                            Price = 8649.687400840372402m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9449),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9414)
                        },
                        new
                        {
                            Id = 13,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9505),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Destination = "East Tad",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9547),
                            Name = "South Reeceborough",
                            Price = 1017.901206423088624m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9544),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9505)
                        },
                        new
                        {
                            Id = 14,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9602),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Destination = "Lake Anibal",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9636),
                            Name = "Jenkinsstad",
                            Price = 8344.059756794519086m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9634),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9602)
                        },
                        new
                        {
                            Id = 15,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9665),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Destination = "North Jewellbury",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9720),
                            Name = "West Clair",
                            Price = 622.3363714832445622m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9718),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9665)
                        },
                        new
                        {
                            Id = 16,
                            BookedSeats = 1,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9758),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Destination = "Lizziehaven",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9793),
                            Name = "Ravenshire",
                            Price = 6912.137088725254759m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9790),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9758)
                        },
                        new
                        {
                            Id = 17,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9862),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Destination = "South Zack",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9894),
                            Name = "Schoenburgh",
                            Price = 5232.953230482067012m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9892),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9862)
                        },
                        new
                        {
                            Id = 18,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9925),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Destination = "Port Brody",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9985),
                            Name = "Marcelletown",
                            Price = 484.3754505454085299m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9982),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 410, DateTimeKind.Local).AddTicks(9925)
                        },
                        new
                        {
                            Id = 19,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 411, DateTimeKind.Local).AddTicks(15),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Destination = "East Delaneyshire",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 411, DateTimeKind.Local).AddTicks(76),
                            Name = "South Chayashire",
                            Price = 3056.715550647183754m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 411, DateTimeKind.Local).AddTicks(73),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 411, DateTimeKind.Local).AddTicks(15)
                        },
                        new
                        {
                            Id = 20,
                            BookedSeats = 0,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 411, DateTimeKind.Local).AddTicks(113),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Destination = "Oberbrunnerside",
                            EndDate = new DateTime(2023, 5, 3, 19, 53, 4, 411, DateTimeKind.Local).AddTicks(145),
                            Name = "South Orlando",
                            Price = 470.6161373239435693m,
                            Seats = 1,
                            StartDate = new DateTime(2023, 4, 28, 19, 53, 4, 411, DateTimeKind.Local).AddTicks(143),
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 411, DateTimeKind.Local).AddTicks(113)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 388, DateTimeKind.Local).AddTicks(8478),
                            Email = "Freddie.Langosh8@hotmail.com",
                            Name = "Dolly.Cummerata30",
                            Password = "TvwNxtZg7Jqb/JeS93S/L1kgqaE5UQ0oo/ZQIEKzB0U=",
                            Role = 0,
                            Salt = "QGRv9+fnS4jzJooSUwhAdlm3W4TdLSYVmXEDdv6c79o=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 388, DateTimeKind.Local).AddTicks(8567)
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 389, DateTimeKind.Local).AddTicks(8929),
                            Email = "Carolina64@gmail.com",
                            Name = "Allie82",
                            Password = "olexg6eK41XV4VuS84BwPWJJpEblzdpKeqYvyh99dQY=",
                            Role = 0,
                            Salt = "TgCmniITFsmW8e6B6wccJXUUVNVOGeDBjD60zkeY7KM=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 389, DateTimeKind.Local).AddTicks(8936)
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 390, DateTimeKind.Local).AddTicks(9233),
                            Email = "Newell.Dach@gmail.com",
                            Name = "Abel10",
                            Password = "+iY55BAoYTAbH/FvI4bitXw2x4KWBkiGToy9r56VHe4=",
                            Role = 1,
                            Salt = "xNachfFQsOIL2Mg2BOa/a0KSUJMeI5MOhR26et6Onjw=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 390, DateTimeKind.Local).AddTicks(9239)
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 391, DateTimeKind.Local).AddTicks(9308),
                            Email = "Loren96@yahoo.com",
                            Name = "Lyric10",
                            Password = "sNT6m0jkQQ8YBRkc02fJzS6QZXSbYXdJEfLC8ZnNT6Q=",
                            Role = 0,
                            Salt = "lvdN6HHTXpRJ7nSehTm/jy4mhaU4NALXhBvoZNA+0jA=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 391, DateTimeKind.Local).AddTicks(9311)
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 392, DateTimeKind.Local).AddTicks(9421),
                            Email = "Juliana.Connelly69@gmail.com",
                            Name = "Jewel42",
                            Password = "969KHjEp93aczx/TqrvzN14XvAR/jms6sw0ue9T5kAs=",
                            Role = 1,
                            Salt = "c3BgTDYWPPVZ2b2y4POW0qbTGZ+bW+FrITP94FBn/lQ=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 392, DateTimeKind.Local).AddTicks(9425)
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 393, DateTimeKind.Local).AddTicks(9541),
                            Email = "Mckenzie_Johnston12@gmail.com",
                            Name = "Amiya_Bednar83",
                            Password = "Z++OKOGTtmpJeJGZcBaUqtuqpuRjtFap6DTK/yW2qe0=",
                            Role = 1,
                            Salt = "hO/TcFesmbrJoB8M5nZT6SuRju/bTyzMTTlWerIk4g4=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 393, DateTimeKind.Local).AddTicks(9545)
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 394, DateTimeKind.Local).AddTicks(9772),
                            Email = "Kaylin71@yahoo.com",
                            Name = "Anahi_Kihn",
                            Password = "mw4mVfywWBVzRLPonHFzuK7irhWBjFcSbQs5jqV1YoI=",
                            Role = 1,
                            Salt = "CBnWCGM6ZZhoM7a6iFa+CsbqIoBwOheb+PGHBNoRnPo=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 394, DateTimeKind.Local).AddTicks(9778)
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 395, DateTimeKind.Local).AddTicks(9917),
                            Email = "Braden_Crooks60@gmail.com",
                            Name = "Art_Wiegand24",
                            Password = "iscvI8XzGgbuRk7XQ/VtZcKTOS5Oiizu+lEPYVya8bY=",
                            Role = 1,
                            Salt = "28AQIePYkUbvN3DC6tteFXEGLsnF5KWbzbEcEHjFWd8=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 395, DateTimeKind.Local).AddTicks(9921)
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 397, DateTimeKind.Local).AddTicks(50),
                            Email = "Benton_Thiel64@gmail.com",
                            Name = "Lance20",
                            Password = "UoORWhB6+0NclyRW4iCJ2VMnQJYTZHUTrX1CSnB5Frs=",
                            Role = 1,
                            Salt = "jjcZnlMQtsjpbVgxgyzMI74uTF7WiShY5RUi/PwaE3c=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 397, DateTimeKind.Local).AddTicks(54)
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 398, DateTimeKind.Local).AddTicks(124),
                            Email = "Anibal_Kihn@yahoo.com",
                            Name = "Anna.Crist",
                            Password = "6DjgThOx8hdfdunZJthftEPTWhEgDKvT6uRFq7yFUSk=",
                            Role = 1,
                            Salt = "vd+zF82USTYovXwfCX+Qx4MO8d4GX9JESERvynThri4=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 398, DateTimeKind.Local).AddTicks(128)
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 399, DateTimeKind.Local).AddTicks(155),
                            Email = "Brady_Morissette@gmail.com",
                            Name = "Maximillia54",
                            Password = "8C4rMkmchXRRJeAfQEbGmNTCOKIJzfdwXK3d6oL9/tA=",
                            Role = 0,
                            Salt = "gQ8b5YwT5v7f6k81ygYlrbnkZ+xOWqlZCgqOIUSCxjY=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 399, DateTimeKind.Local).AddTicks(159)
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 400, DateTimeKind.Local).AddTicks(307),
                            Email = "Constantin.Marks73@gmail.com",
                            Name = "Della.Powlowski",
                            Password = "Dg3fkf6+4EJ9SqdPM0ZyjjqNLQ1iqf0JpGO2CN75xcg=",
                            Role = 0,
                            Salt = "5p1ujs6PZbJr+ViJhBfXUtX7r7a5crJbKHiVVi4Ocd4=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 400, DateTimeKind.Local).AddTicks(311)
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 401, DateTimeKind.Local).AddTicks(402),
                            Email = "Wiley_Borer19@hotmail.com",
                            Name = "Kenyon63",
                            Password = "DE6/dhsMlbb96hW9hGAc6m61p941ASjlDcFT3XoawSw=",
                            Role = 1,
                            Salt = "auLfSssY/cUEJ/1458A4L+IiHN6W0YLq2GT3I5LAcp0=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 401, DateTimeKind.Local).AddTicks(406)
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 402, DateTimeKind.Local).AddTicks(444),
                            Email = "Narciso39@yahoo.com",
                            Name = "Emilie.Block33",
                            Password = "ZapHgy2xilXrMF1A3cwW21uTlZVPcdZerWF1/kwcZ3Q=",
                            Role = 1,
                            Salt = "Q1LO92cPsik+HoOEeSxeO/SKmj0hHUZCiHcdiAvchB4=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 402, DateTimeKind.Local).AddTicks(447)
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 403, DateTimeKind.Local).AddTicks(563),
                            Email = "Rickie.Kling69@gmail.com",
                            Name = "Danny88",
                            Password = "kxXhYJeXRF15vAAfQU/VUqEsTrX18Y28al/B9UYtXg0=",
                            Role = 1,
                            Salt = "zhh+lfFOYQ480+SXNRJYQBE/kNnH4ZYfJ1R6sFPPmhM=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 403, DateTimeKind.Local).AddTicks(567)
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 404, DateTimeKind.Local).AddTicks(619),
                            Email = "Unique.Herzog@hotmail.com",
                            Name = "Murl30",
                            Password = "+c9eIH8SafqNdbzzQrN0Pkzpxk9FZhz/uYPEeTwZU+8=",
                            Role = 0,
                            Salt = "9Eg2wrYhX/yqZHSPsmiY3GXRize9Lh7GUmTM2USFC7Y=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 404, DateTimeKind.Local).AddTicks(623)
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 405, DateTimeKind.Local).AddTicks(666),
                            Email = "Arden94@yahoo.com",
                            Name = "Valentin_Jacobs",
                            Password = "og2wptUGl5n/9IOatJAzlrmGMUBKPg1IK5QSxVsGcYE=",
                            Role = 1,
                            Salt = "jcbuloy4J07MHukq1wbpYIXULibJV813lDcCPFBSYJ0=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 405, DateTimeKind.Local).AddTicks(670)
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 406, DateTimeKind.Local).AddTicks(819),
                            Email = "Judd4@yahoo.com",
                            Name = "Gertrude28",
                            Password = "8PEVtsQ19DmdWcWvXIsCtsqNcdfE/YcTLFDhIGRlo9o=",
                            Role = 1,
                            Salt = "JbtAwOwnLxNHNTK/i9U1R5f2DK4TEnSa0J2YYeNfP/8=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 406, DateTimeKind.Local).AddTicks(823)
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 407, DateTimeKind.Local).AddTicks(885),
                            Email = "Drew_Spencer@hotmail.com",
                            Name = "Euna50",
                            Password = "8LTAz32Smk4R0/vhzMpRAD814lVDl3ZTDTwBi9adwkY=",
                            Role = 0,
                            Salt = "D/8lWogXPBy1nMfsscXi4Nq1bM/CbABbaYFSKEhc91A=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 407, DateTimeKind.Local).AddTicks(888)
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 408, DateTimeKind.Local).AddTicks(966),
                            Email = "Murphy95@yahoo.com",
                            Name = "Penelope.Fay16",
                            Password = "5SH+qZCjPxl/+G8hymS1KNJ6904FCzF6K5Pw7bBPcsI=",
                            Role = 0,
                            Salt = "jvpN/K5+UGmxNZzd/8bGk8yO7OHossBZY4BJz6jGcSI=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 408, DateTimeKind.Local).AddTicks(970)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 409, DateTimeKind.Local).AddTicks(982),
                            Email = "test@gmail.com",
                            Name = "testUser",
                            Password = "/Atrz9u4h/IH8/FGNMgPxL74qw/N4gBg9nnJGCQUsRU=",
                            Role = 0,
                            Salt = "B77btj8BvaWXoFQsYsCvKGJNMKr9suAy+nPBK4lxtaI=",
                            UpdatedAt = new DateTime(2023, 4, 28, 19, 53, 4, 409, DateTimeKind.Local).AddTicks(982)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RefreshToken", b =>
                {
                    b.HasOne("BookTouristRoutes.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.User", b =>
                {
                    b.HasOne("BookTouristRoutes.Common.Models.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });
#pragma warning restore 612, 618
        }
    }
}
