// <auto-generated />
using System;
using BookTouristRoutes.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookTouristRoutes.DAL.Migrations
{
    [DbContext(typeof(BookTouristRoutesContext))]
    [Migration("20230424113532_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookTouristRoutes.Common.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8650),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1100.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8689)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8724),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/719.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8727)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8736),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/481.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8738)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8746),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/646.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8747)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8755),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/458.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8757)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8764),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/487.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8765)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8774),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/498.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8776)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8783),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/749.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8785)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8793),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/347.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8794)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8801),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/261.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8803)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8810),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/770.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8812)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8820),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/378.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8822)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8829),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/301.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8831)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8839),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/565.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8840)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8848),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1117.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8850)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8857),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/4.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8859)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8866),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/961.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8868)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8875),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/300.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8876)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8884),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1108.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8886)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8933),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/879.jpg",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 838, DateTimeKind.Local).AddTicks(8935)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7362),
                            URL = "https://picsum.photos/640/480/?image=953",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7394)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7427),
                            URL = "https://picsum.photos/640/480/?image=891",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7430)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7440),
                            URL = "https://picsum.photos/640/480/?image=267",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7442)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7450),
                            URL = "https://picsum.photos/640/480/?image=862",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7452)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7462),
                            URL = "https://picsum.photos/640/480/?image=707",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7464)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7472),
                            URL = "https://picsum.photos/640/480/?image=683",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7474)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7509),
                            URL = "https://picsum.photos/640/480/?image=233",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7511)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7521),
                            URL = "https://picsum.photos/640/480/?image=77",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7522)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7530),
                            URL = "https://picsum.photos/640/480/?image=962",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7532)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7539),
                            URL = "https://picsum.photos/640/480/?image=444",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7541)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7549),
                            URL = "https://picsum.photos/640/480/?image=857",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7551)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7558),
                            URL = "https://picsum.photos/640/480/?image=35",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7560)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7568),
                            URL = "https://picsum.photos/640/480/?image=117",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7570)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7578),
                            URL = "https://picsum.photos/640/480/?image=196",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7579)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7587),
                            URL = "https://picsum.photos/640/480/?image=82",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7589)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7597),
                            URL = "https://picsum.photos/640/480/?image=450",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7599)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7607),
                            URL = "https://picsum.photos/640/480/?image=434",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7608)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7617),
                            URL = "https://picsum.photos/640/480/?image=880",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7619)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7627),
                            URL = "https://picsum.photos/640/480/?image=543",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7629)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7637),
                            URL = "https://picsum.photos/640/480/?image=734",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 840, DateTimeKind.Local).AddTicks(7639)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookedSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 843, DateTimeKind.Local).AddTicks(5874),
                            Email = "Hans.Runolfsdottir58@gmail.com",
                            Name = "Tina_Swift73",
                            Password = "2QCQK51QkT417kb3azxhb3e2I71J6S8xdgoy94L7dRw=",
                            Roles = 0,
                            Salt = "Ku/9M0VkaJrw7JT1QaoEpGYIkXNVhf6WTN82yXpBZ4Y=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 843, DateTimeKind.Local).AddTicks(5963)
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 844, DateTimeKind.Local).AddTicks(6381),
                            Email = "Alexys1@hotmail.com",
                            Name = "Dena96",
                            Password = "xtkYempDuO8wrRZ6Irb9/JRo217LK+fr4zKe3YGsDJE=",
                            Roles = 0,
                            Salt = "z7re9nhK7zOtmDSvTB1yaRrmHi5i6Kap9ckaWGc4Pls=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 844, DateTimeKind.Local).AddTicks(6388)
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 845, DateTimeKind.Local).AddTicks(6515),
                            Email = "Marina91@gmail.com",
                            Name = "Tevin.Nicolas76",
                            Password = "+F9oXT84dr7QrtByrMnjOkgNqJ39aem6i/C8YxO6WOg=",
                            Roles = 1,
                            Salt = "hBeLakt7IlF64lLit0r3w4XG96eUByoVR3I+f6b4aa4=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 845, DateTimeKind.Local).AddTicks(6518)
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 846, DateTimeKind.Local).AddTicks(6620),
                            Email = "Clare.Langosh82@gmail.com",
                            Name = "Jerry79",
                            Password = "TH23dbTHfBxTlS6NPScXDsJ9t3XyBJpMGQziI2Yp4YU=",
                            Roles = 0,
                            Salt = "6CrncdT4YtEwoJhEjaEdAiqlonYBvq9OXNi4NaNNuBs=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 846, DateTimeKind.Local).AddTicks(6623)
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 847, DateTimeKind.Local).AddTicks(6861),
                            Email = "Katelyn53@hotmail.com",
                            Name = "Floyd_Casper",
                            Password = "Hk/w6pdmMGsdVHhvoMX7obTtpiSbdRK9XUc8yvSkL3k=",
                            Roles = 1,
                            Salt = "H+7eWzRdPfNof5oHufqZPyg63Vz4uesNIuZnh98h6ts=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 847, DateTimeKind.Local).AddTicks(6867)
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 848, DateTimeKind.Local).AddTicks(7215),
                            Email = "Maverick.Kris@gmail.com",
                            Name = "Rogers_Ruecker",
                            Password = "SLmuvljQS+Acwp+2BPihWFgllTAdQ2JNatabDh/jMLE=",
                            Roles = 0,
                            Salt = "pfS3PvdYYwqbMNYn/MkC1yUiDk9TP1HGmxnF+G4fG/I=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 848, DateTimeKind.Local).AddTicks(7220)
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 849, DateTimeKind.Local).AddTicks(7272),
                            Email = "Tamara3@yahoo.com",
                            Name = "Wilma23",
                            Password = "gCjcv4w0aZD7qKb7OJkSH/nFLCntlfqNfoAmjCNuDRg=",
                            Roles = 1,
                            Salt = "4yJEkaU+iD9BG5V0DnVUFru2wefjjy41/yU6pKsuNV4=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 849, DateTimeKind.Local).AddTicks(7276)
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 850, DateTimeKind.Local).AddTicks(7530),
                            Email = "Vivian.Heller47@yahoo.com",
                            Name = "Bud_Waters",
                            Password = "v1OhNMLY4B17ng+0zMAiEvf8MLQF0ZiSezRrfpL+UWQ=",
                            Roles = 0,
                            Salt = "8zocJaMSIdxUvUNUwb7nC7fpysTCm6GYVhdVmr7c2mQ=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 850, DateTimeKind.Local).AddTicks(7534)
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 851, DateTimeKind.Local).AddTicks(7747),
                            Email = "Twila10@hotmail.com",
                            Name = "Davin64",
                            Password = "dXAW5HAb69+wJaIY59r1nLeTh8Zd5gXP32U7ZAIBj+c=",
                            Roles = 1,
                            Salt = "hSG5HX+qGtqMhNgjQiKJj4TY3DF1FjpH3FZX13Ab67A=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 851, DateTimeKind.Local).AddTicks(7751)
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 852, DateTimeKind.Local).AddTicks(7743),
                            Email = "Moshe.Schowalter@gmail.com",
                            Name = "Vita.West64",
                            Password = "vwhlOwdYAg4+uVo+RifDAh3AgGReBn8b+/ZETM6Dtec=",
                            Roles = 1,
                            Salt = "+ObI/9cC5qEE+Gybz2p5yvCaTia6I6/feVQoRT8ubaI=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 852, DateTimeKind.Local).AddTicks(7747)
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 853, DateTimeKind.Local).AddTicks(7831),
                            Email = "Brown.Graham@hotmail.com",
                            Name = "Tara_Ledner",
                            Password = "m6wnzvBVjmn94mLpCjA2b7GsfGZdHyJja/kivSKNW6s=",
                            Roles = 1,
                            Salt = "GTdvWext+9boWDpixu+PEwjnmU7wlUDayIQCC0kuPaU=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 853, DateTimeKind.Local).AddTicks(7834)
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 854, DateTimeKind.Local).AddTicks(7965),
                            Email = "Malika65@yahoo.com",
                            Name = "Beverly.Gleason",
                            Password = "W7X3UfoCGr9XRZc+zWW9alOdrXvSt1gunbuaAOu1XIQ=",
                            Roles = 0,
                            Salt = "C/lkMRVHR2tITdSdihqg2UxYbhNBz0SlS+4ZymrsYAo=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 854, DateTimeKind.Local).AddTicks(7968)
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 855, DateTimeKind.Local).AddTicks(8114),
                            Email = "Dennis27@yahoo.com",
                            Name = "Otho.Mosciski",
                            Password = "YHzm22ni0/QuOnPXJY7EL1OdoCcLkWdE8Cdt+/uyMMg=",
                            Roles = 1,
                            Salt = "rGz8h7fyCuMy9BLcblCr5S1jpW64WmQzi39kGWsx13k=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 855, DateTimeKind.Local).AddTicks(8118)
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 856, DateTimeKind.Local).AddTicks(8285),
                            Email = "Else_Ferry51@hotmail.com",
                            Name = "Zora79",
                            Password = "hnNxZtfiloaI+E2k2ow8jSyZKjcDX8LEvLeg5X3cHaM=",
                            Roles = 0,
                            Salt = "2zQgni7pc4br5iI2cZ/MBLHq+W4AOZWzyE0AHPRCMq8=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 856, DateTimeKind.Local).AddTicks(8288)
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 857, DateTimeKind.Local).AddTicks(8351),
                            Email = "Korey.Walsh63@hotmail.com",
                            Name = "Hillary99",
                            Password = "JbwgQRLAyJUIRARs59cIDNPB/U+ckZ2WwIrvTI6wVy8=",
                            Roles = 0,
                            Salt = "OjmJpCRwaxWEix1DbALwIqS6Azl8cydQ9rOW23greKU=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 857, DateTimeKind.Local).AddTicks(8354)
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 858, DateTimeKind.Local).AddTicks(8634),
                            Email = "Pattie.Gleason26@yahoo.com",
                            Name = "Braxton77",
                            Password = "vx1B/dLZ+6ehv8qLRHVYomT7S8UvQQPs+wCb+XDLwaY=",
                            Roles = 0,
                            Salt = "OUe5RYJTBeYHSbzbldkRWdTSGoyfvYtCSjl8E/ybLL4=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 858, DateTimeKind.Local).AddTicks(8638)
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 859, DateTimeKind.Local).AddTicks(8695),
                            Email = "Luther26@gmail.com",
                            Name = "Madelyn.Wiza73",
                            Password = "TcRq7kLmv/L11pWoyxGk6s7Abo+c+VKOjQvG+tdgxxI=",
                            Roles = 0,
                            Salt = "sKveKL3us0nBnTkpWR6L7NhWt7gLA61simm1HJjR1ss=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 859, DateTimeKind.Local).AddTicks(8698)
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 860, DateTimeKind.Local).AddTicks(8850),
                            Email = "Berry83@yahoo.com",
                            Name = "Margret.Halvorson54",
                            Password = "NSj88WBODcINZTaUrITiXkrjjWrn3+buskXyg1qv+V0=",
                            Roles = 0,
                            Salt = "/90Sd5Fgq/Sxn0qcIjb6adfGouxOgW6eKXS2kYKGIJE=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 860, DateTimeKind.Local).AddTicks(8856)
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 861, DateTimeKind.Local).AddTicks(8943),
                            Email = "Aniya2@hotmail.com",
                            Name = "Viviane56",
                            Password = "reDr6lm9OSxPE8KZ32k8WMt4HIJaHhoG9FT4u5oavPw=",
                            Roles = 1,
                            Salt = "uB4o9lwMfDiNffOennaBO3MZA2AVxqWXIC/BcX2o1FA=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 861, DateTimeKind.Local).AddTicks(8946)
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 862, DateTimeKind.Local).AddTicks(9083),
                            Email = "Marjorie18@yahoo.com",
                            Name = "Cydney_Parker89",
                            Password = "z3MRfr8Pkd82J6dAX2J+jBbTHKM3kE2S3EI7Okcbbrs=",
                            Roles = 0,
                            Salt = "4EKjcb0LeJqiy3YOq2EvQQft4XjeemtcaSva6YtQLC8=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 862, DateTimeKind.Local).AddTicks(9086)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 863, DateTimeKind.Local).AddTicks(9127),
                            Email = "test@gmail.com",
                            Name = "testUser",
                            Password = "UBUXfehO8LgYvC39FrIqs+YZ8pR8ihq0YlHVsSaWynU=",
                            Roles = 0,
                            Salt = "sTqHIXQYRnrX6ForbhKLtQcZicmwd5geyeGa5KpYYDs=",
                            UpdatedAt = new DateTime(2023, 4, 24, 14, 35, 32, 863, DateTimeKind.Local).AddTicks(9127)
                        });
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.RefreshToken", b =>
                {
                    b.HasOne("BookTouristRoutes.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookTouristRoutes.Common.Models.User", b =>
                {
                    b.HasOne("BookTouristRoutes.Common.Models.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });
#pragma warning restore 612, 618
        }
    }
}
